#ifndef _SNEERA_PREFETCH_H
#define _SNEERA_PREFETCH_H


/*
 * Portable prefetch — compiler detection chain.
 * Always: read prefetch, non-temporal (locality 0).
 * Falls back to a no-op (void cast) on unknown compilers —
 * a no-op is always correct, just not optimal.
 *
 * Detection ORDER matters:
 *   ICC defines __GNUC__ for compatibility — must be caught first.
 *   ARM Compiler 6 is clang-based — caught by __clang__ branch.
 *   ARM Compiler 5 (armcc) defines __CC_ARM / __ARMCC_VERSION.
 *
 * --- this macro was generated by Claude Sonnet 4.6 Extended ---
 */
#if !defined(prefetch_read)

#if defined(__INTEL_COMPILER) || defined(__ICL) || defined(__ICC)
   #include <immintrin.h>
   #define prefetch_read(addr) \
      _mm_prefetch((const char *)(addr), _MM_HINT_NTA)

#elif defined(__GNUC__) || defined(__clang__)
   #define prefetch_read(addr) \
      __builtin_prefetch((addr), 0, 0)

#elif defined(_MSC_VER)
   #include <intrin.h>
   #if defined(_M_ARM) || defined(_M_ARM64)
      #define prefetch_read(addr) \
         __prefetch(addr)
   #else
      #define prefetch_read(addr) \
         _mm_prefetch((const char *)(addr), _MM_HINT_NTA)
   #endif

#elif defined(__CC_ARM) || (defined(__ARMCC_VERSION) && !defined(__clang__))
   #define prefetch_read(addr) \
      __pld(addr)

#elif defined(__SUNPRO_C) || defined(__SUNPRO_CC)
   #if defined(__sparc) || defined(__sparc__)
      #define prefetch_read(addr) \
         __asm__ volatile ("prefetch [%0], 1" : : "r" (addr))
   #else
      #include <immintrin.h>
      #define prefetch_read(addr) \
         _mm_prefetch((const char *)(addr), _MM_HINT_NTA)
   #endif

#else
   #define prefetch_read(addr) \
      ((void)(addr))

#endif

#endif /* prefetch_read */


#endif /* _SNEERA_PREFETCH_H */
